apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-dns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: private-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: private-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: private-dns
subjects:
- kind: ServiceAccount
  name: private-dns
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: private-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: private-dns
        aadpodidbinding: kh-c2-privatedns
    spec:
      serviceAccountName: private-dns
      containers:
      - name: private-dns
        image: khowling/private-dns:0.4
        env:
        - name: AZURE_GO_SDK_LOG_LEVEL
          value: "DEBUG"
        args:
        - --azure-resource-group=kh-aks
        - --azure-subscription-id=95efa97a-9b5d-4f74-9f75-a3396e23344d
