apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ template "azure-dns-controller.azureidbinding" . }}
spec:
  AzureIdentity: {{ template "azure-dns-controller.azureidentity" . }}
  Selector: {{ template "azure-dns-controller.fullname" . }}
